name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/train_pca.csv"
  TARGET_VAR: "Credit_Score"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL
      # Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow  
          
      # Run as a mlflow project
      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local 
      
      # Get latest run_id
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"
          
      - name: Install Python dependencies
        run: |
          pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
        
      - name: Upload to Google Drive
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}  # Mengambil kredensial dari GitHub Secrets
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}  # Mengambil kredensial dari GitHub Secrets
        run: |
          python MLproject/upload_to_gdrive.py

          
      # Build Docker Model
      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "cc" 

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Tag the Docker image
      - name: Tag Docker Image
        run: |
          docker tag cc ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest

      # Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest
      
      # # Get latest run_id
      # - name: Get latest MLflow run_id
      #   run: |
      #     RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
      #     echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
      #     echo "Latest run_id: $RUN_ID"

      # # Copy MLflow artifacts to temporary storage
      # - name: Copy MLflow Artifacts to Temporary Storage
      #   run: |
      #     TEMP_DIR="$RUNNER_TEMP/mlflow_artifacts"
      #     mkdir -p $TEMP_DIR
      #     cp -r mlruns/0/${{ env.RUN_ID }}/artifacts/* $TEMP_DIR/
      #     echo "Artifacts copied to $TEMP_DIR"

      # # Copy app.py and preprocessAPI.py to the same directory
      # - name: Copy app.py and preprocessAPI.py to Temporary Storage
      #   run: |
      #     cp app.py preprocessAPI.py $RUNNER_TEMP/mlflow_artifacts/
      #     echo "app.py and preprocessAPI.py copied to $RUNNER_TEMP/mlflow_artifacts/"

      # # Print MLflow artifacts directory structure
      # - name: Print MLflow Artifacts Directory Structure
      #   run: |
      #     echo "MLflow Artifacts Structure:"
      #     ls -R $RUNNER_TEMP/mlflow_artifacts/