name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/train_pca.csv"
  TARGET_VAR: "Credit_Score"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL
      # Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow dagshub 
          
      # Run as a mlflow project
      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local 
  upload-artifacts:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Retrieve MLflow artifacts directory (default: mlruns/)
      - name: Find MLflow Artifacts
        run: |
          echo "Listing MLflow directory..."
          ls -R mlruns || echo "No artifacts found"

      # Upload MLflow artifacts
      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mlflow-artifacts
          path: mlruns/